[build]
  command = "npm install"
  functions = "functions"
  publish = "/"
[functions]
  external_node_modules = ["express", "pug", "express-session"]
  node_bundler = "esbuild"
  included_files = ["views/**/*.pug", "public/**/*", "controlador/**/*", "db/**/*", "models/**/*", "routes/**/*"]
[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/api/:splat"


