[build]
  command = "npm install"
  functions = "functions"
[functions]
  external_node_modules = ["express", "pug"]
  node_bundler = "esbuild"
  included_files = ["views/*.pug"]
[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

